import { createRemoteJWKSet, jwtVerify } from 'jose'
import { neon as postgres } from '@neondatabase/serverless'
import { createUserStore, createRegistrar, validateNewUser, validateMember } from './users.js'
export class ApiError extends Error { constructor(status,message){super(message);this.status=status} }
async function readJson(req){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>10*1024*1024)throw new ApiError(413,'Dados muito grandes.');chunks.push(chunk)}try{return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}')}catch{throw new ApiError(400,'JSON inválido.')}}
export function createVerifier(authUrl){const base=authUrl.replace(/\/$/,'');const origin=new URL(base).origin;const keys=createRemoteJWKSet(new URL(`${base}/.well-known/jwks.json`));return async token=>(await jwtVerify(token,keys,{issuer:[origin,`${origin}/`,base],audience:origin,algorithms:['EdDSA','ES256','RS256'],requiredClaims:['sub','exp','iat'],clockTolerance:5})).payload.sub}
export function validState(s){if(!s||typeof s!=='object'||!s.settings)throw new ApiError(400,'Estrutura de dados inválida.');for(const k of ['clients','trips','sales']){if(!Array.isArray(s[k]))throw new ApiError(400,`Lista inválida: ${k}.`);const ids=new Set();for(const x of s[k]){if(!x?.id||ids.has(x.id))throw new ApiError(400,`Identificador inválido em ${k}.`);ids.add(x.id)}}return s}
export function withoutCommissions(state){const{commissionRate,...settings}=state.settings||{};return{...state,settings,sales:(state.sales||[]).map(({commissionRate:legacyRate,...sale})=>sale)}}
export function preserveCommissions(next,current){const rates=new Map((current.sales||[]).map(s=>[s.id,s.commissionRate]));return{...next,settings:{...(next.settings||{}),...(current.settings?.commissionRate!==undefined?{commissionRate:current.settings.commissionRate}:{})},sales:(next.sales||[]).map(({commissionRate,...sale})=>({...sale,...(rates.has(sale.id)&&rates.get(sale.id)!==undefined?{commissionRate:rates.get(sale.id)}:{})}))}}
export function createStore(url){const sql=postgres(url);return{sql,async read(id){const r=await sql`select version,state from public.app_state where id=1 and exists(select 1 from public.app_members where user_id=${id})`;return r[0]?{version:Number(r[0].version),state:r[0].state}:null},async write(id,v,state){const r=await sql`update public.app_state set state=${JSON.stringify(state)}::jsonb,version=version+1 where id=1 and version=${v} and exists(select 1 from public.app_members where user_id=${id}) returning version,state`;return r[0]?{version:Number(r[0].version),state:r[0].state}:{conflict:true}},async publicLookup(cpf){const r=await sql`select state from public.app_state where id=1`;const s=r[0]?.state||{};const digits=String(cpf||'').replace(/\D/g,'');const client=(s.clients||[]).find(c=>String(c.cpf||'').replace(/\D/g,'')===digits);if(!client)return null;return{client:{name:client.name,cpf:client.cpf,phone:client.phone,email:client.email},sales:(s.sales||[]).filter(x=>x.clientId===client.id&&x.status!=='Cancelada').map(x=>{const trip=(s.trips||[]).find(t=>t.id===x.tripId)||{};return{reservation:x.reservation,status:x.status,total:x.total,createdAt:x.createdAt,trip:{title:trip.title,departureDate:trip.departureDate,returnDate:trip.returnDate,destination:trip.destination},passengers:1+(x.dependents||[]).length}})}}}}
const attempts=new Map();function allow(ip){const now=Date.now(),row=attempts.get(ip)||{at:now,count:0};if(now-row.at>60000){row.at=now;row.count=0}row.count++;attempts.set(ip,row);return row.count<=15}
export function createApi({authUrl,databaseUrl}={}){const verify=authUrl?createVerifier(authUrl):null,db=databaseUrl?createStore(databaseUrl):null,members=db?createUserStore(db.sql):null,register=authUrl?createRegistrar(authUrl):null;return async(req,res,next=()=>{res.writeHead(404);res.end()})=>{const path=new URL(req.url,'http://local').pathname;const send=(status,body)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(body))};if(!path.startsWith('/api/'))return next();if(path==='/api/health')return send(verify&&db?200:503,{configured:Boolean(verify&&db)});if(!verify||!db)return send(503,{message:'Configure VITE_NEON_AUTH_URL e DATABASE_URL.'});try{
    if(path==='/api/public/lookup'&&req.method==='POST'){if(!allow(req.socket.remoteAddress||'unknown'))throw new ApiError(429,'Muitas tentativas. Aguarde um minuto.');const {cpf}=await readJson(req);if(!/^\d{11}$/.test(String(cpf||'').replace(/\D/g,'')))throw new ApiError(400,'Informe um CPF válido.');const data=await db.publicLookup(cpf);if(!data)throw new ApiError(404,'Nenhum cadastro localizado.');return send(200,data)}
    if(path==='/api/bootstrap'&&req.method==='POST'){if(await members.count())throw new ApiError(409,'O acesso inicial já foi criado.');const account={name:'Administrador Rota Viva',email:'admin@rotaviva.com.br',password:'RotaViva@2026'};const existing=await members.idByEmail(account.email);const id=existing||await register(account,req.headers.origin);await members.authorizeFirst(id);return send(201,{ok:true,email:account.email})}
    const match=/^Bearer ([^\s]+)$/.exec(req.headers.authorization||'');if(!match)throw new ApiError(401,'Entre para acessar os dados.');let id;try{id=await verify(match[1])}catch{throw new ApiError(401,'Sessão inválida ou expirada.')}const role=await members.role(id);if(!role)throw new ApiError(403,'Acesso não autorizado.');
    if(path==='/api/me'&&req.method==='GET')return send(200,{id,role});
    if(path==='/api/users'){if(role!=='Administrador')throw new ApiError(403,'Somente administradores gerenciam usuários.');if(req.method==='GET')return send(200,{users:await members.list(id)});const input=await readJson(req);if(req.method==='PUT'){await members.update(id,validateMember(input));return send(200,{ok:true})}if(req.method==='POST'){const a=validateNewUser(input);if(await members.emailExists(a.email))throw new ApiError(409,'E-mail já cadastrado.');const userId=await register(a,req.headers.origin);await members.update(id,{id:userId,role:a.role,active:true});return send(201,{ok:true})}}
    if(path==='/api/state'&&req.method==='GET'){const result=await db.read(id);if(!result)throw new ApiError(403,'Acesso não autorizado.');return send(200,role==='Administrador'?result:{...result,state:withoutCommissions(result.state)})}if(path==='/api/state'&&req.method==='PUT'){const body=await readJson(req);if(!Number.isSafeInteger(body.expected_version))throw new ApiError(400,'Versão inválida.');let next=validState(body.next_state);if(role!=='Administrador'){const current=await db.read(id);if(!current)throw new ApiError(403,'Acesso não autorizado.');next=preserveCommissions(next,current.state)}const result=await db.write(id,body.expected_version,next);return send(200,role==='Administrador'||result.conflict?result:{...result,state:withoutCommissions(result.state)})}throw new ApiError(404,'Rota não encontrada.')
  }catch(error){return send(error.status||500,{message:error instanceof ApiError?error.message:'Não foi possível acessar o banco de dados.'})}}}
